name: Integration Continue

on:
  push:
    branches: ["main", "test"]
  pull_request:
    branches: ["main"]

jobs:
  angular:
    name: test front-end
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: espace-client-frontend

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Setup Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci

      - name: Build
        run: npm run build

  backend-test:
    name: test back-end
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: espace-client-backend

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.CI_DB_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Setup Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build



name: Deployment on Heroku

on:
  push:
    branches: ["test"]


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Choisissez la version de Node.js appropriée

      - name: Install dependencies
        run: |
          npm install

      - name: Build the project
        run: |
          npm run build

      - name: Log in to Heroku
        run: |
          echo "heroku: ${{ secrets.HEROKU_API_KEY }}" | docker login --username=_ --password-stdin registry.heroku.com

      - name: Deploy to Heroku
        run: |
          heroku git:remote -a votre-app-name
          git push heroku main  # Cela va pousser le code vers Heroku
