name: Integration Continue

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  angular:
    name: test front-end
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: espace-client-frontend

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Setup Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci

      - name: Build
        run: npm run build
